spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-52-205-98-159.compute-1.amazonaws.com/de2japqv19a6pu
  username: ckaezsxpfeyqrg
  password: 37730baec7fdf13061437f3b9f2ddf20101f91389a53383e384ec5cff3139ccf
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000







